/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brick:        '#8B2500',
        'brick-mid':  '#C1440E',
        'brick-light':'#E8744A',
        cream:        '#FDF3E0',
        'cream-dark': '#F0D9A8',
        gold:         '#C9962A',
        'nanyang-teal':'#1A6B5A',
        'nanyang-green':'#2C8C6A',
        /* ── Cyber / Futuristic palette ── */
        cyber:          '#030712',
        'cyber-panel':  '#06101f',
        'cyber-card':   '#08152a',
        'cyber-line':   '#0d2d50',
        'neon-cyan':    '#00f0ff',
        'neon-blue':    '#3b7eff',
        'neon-purple':  '#9b5de5',
        'neon-pink':    '#ff007f',
        'neon-gold':    '#fdee30',
        'neon-green':   '#06d6a0',
        'neon-orange':  '#ff6b35',
        'neon-magenta': '#ff00ff',
        'neon-lime':    '#39ff14',
        'neon-acid':    '#fdee30',
        'neon-laser':   '#ff007f',
      },
      fontFamily: {
        chinese:     ['"Noto Serif SC"', '"Source Han Serif CN"', '"STSong"', '"SimSun"', 'serif'],
        orbitron:    ['"Orbitron"', 'sans-serif'],
        'share-tech':['"Share Tech Mono"', 'monospace'],
      },
      keyframes: {
        shake: {
          '0%,100%': { transform: 'translateX(0)' },
          '20%':     { transform: 'translateX(-6px)' },
          '40%':     { transform: 'translateX(6px)' },
          '60%':     { transform: 'translateX(-4px)' },
          '80%':     { transform: 'translateX(4px)' },
        },
        pop: {
          '0%':   { transform: 'scale(1)' },
          '50%':  { transform: 'scale(1.12)' },
          '100%': { transform: 'scale(1)' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(32px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        charEnter: {
          '0%':   { opacity: '0', transform: 'scale(0.7) translateY(20px)' },
          '60%':  { transform: 'scale(1.08) translateY(-4px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        flashGreen: {
          '0%,100%': { boxShadow: '0 0 0px rgba(26,107,90,0)' },
          '50%':     { boxShadow: '0 0 24px 8px rgba(26,107,90,0.55)' },
        },
        flashRed: {
          '0%,100%': { boxShadow: '0 0 0px rgba(139,37,0,0)' },
          '50%':     { boxShadow: '0 0 24px 8px rgba(139,37,0,0.55)' },
        },
        pulse2: {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0.2' },
        },
        coinFloat: {
          '0%':   { opacity: '0', transform: 'translateY(20px) scale(0.6)' },
          '15%':  { opacity: '1', transform: 'translateY(-4px) scale(1.18)' },
          '30%':  { opacity: '1', transform: 'translateY(0) scale(1)' },
          '75%':  { opacity: '1', transform: 'translateY(-8px) scale(1)' },
          '100%': { opacity: '0', transform: 'translateY(-40px) scale(0.85)' },
        },
        wiggle: {
          '0%,100%': { transform: 'rotate(0deg)' },
          '25%':     { transform: 'rotate(-6deg)' },
          '75%':     { transform: 'rotate(6deg)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 50%' },
          '100%': { backgroundPosition: '200% 50%' },
        },
        bounceCoin: {
          '0%,100%': { transform: 'translateY(0) rotate(0)' },
          '50%':     { transform: 'translateY(-4px) rotate(8deg)' },
        },
        confettiPop: {
          '0%':   { opacity: '0', transform: 'translate(0,0) scale(0)' },
          '20%':  { opacity: '1', transform: 'translate(var(--cx,0),var(--cy,0)) scale(1)' },
          '100%': { opacity: '0', transform: 'translate(calc(var(--cx,0)*1.4),calc(var(--cy,0)*1.4 + 60px)) scale(0.6) rotate(180deg)' },
        },
        glow: {
          '0%,100%': { boxShadow: '0 0 8px rgba(253,238,48,0.4)' },
          '50%':     { boxShadow: '0 0 24px rgba(253,238,48,0.9)' },
        },
        neonPulse: {
          '0%,100%': { boxShadow: '0 0 6px rgba(0,240,255,0.5), 0 0 12px rgba(0,240,255,0.2)' },
          '50%':     { boxShadow: '0 0 20px rgba(0,240,255,1), 0 0 40px rgba(0,240,255,0.5)' },
        },
        cyberGlow: {
          '0%,100%': { opacity: '0.6' },
          '50%':     { opacity: '1' },
        },
        scanLine: {
          '0%':   { transform: 'translateY(-100vh)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        titleFlicker: {
          '0%,95%,100%': { opacity: '1' },
          '97%':         { opacity: '0.85' },
        },
        borderFlow: {
          '0%':   { backgroundPosition: '0% 50%' },
          '50%':  { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        floatY: {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%':     { transform: 'translateY(-8px)' },
        },
        cyberFadeIn: {
          from: { opacity: '0', transform: 'translateY(16px) scale(0.97)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        explode: {
          '0%':   { opacity: '1', transform: 'scale(1)' },
          '40%':  { opacity: '1', transform: 'scale(1.6)' },
          '100%': { opacity: '0', transform: 'scale(2.2)' },
        },
        laserShot: {
          '0%':   { opacity: '0', transform: 'scaleY(0)', transformOrigin: 'bottom' },
          '20%':  { opacity: '1', transform: 'scaleY(1)', transformOrigin: 'bottom' },
          '100%': { opacity: '0', transform: 'scaleY(1)', transformOrigin: 'bottom' },
        },
        particleFly: {
          '0%':   { opacity: '1', transform: 'translate(0,0) scale(1)' },
          '100%': { opacity: '0', transform: 'translate(var(--px,0),var(--py,0)) scale(0.3) rotate(180deg)' },
        },
        starTwinkle: {
          '0%,100%': { opacity: '0.3' },
          '50%':     { opacity: '0.9' },
        },
        shipFloat: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%':     { transform: 'translateY(-4px)' },
        },
        blink: {
          '0%,88%,100%': { transform: 'scaleY(1)' },
          '92%':         { transform: 'scaleY(0.08)' },
          '96%':         { transform: 'scaleY(1)' },
        },
        equipBounce: {
          '0%':   { transform: 'translateY(0) scale(1)' },
          '28%':  { transform: 'translateY(-18px) scale(1.08) rotate(-2deg)' },
          '55%':  { transform: 'translateY(-7px) scale(1.04) rotate(1.5deg)' },
          '78%':  { transform: 'translateY(-2px) scale(1.01)' },
          '100%': { transform: 'translateY(0) scale(1)' },
        },
        starFloat: {
          '0%,100%': { transform: 'translateY(0)', opacity: '0.5' },
          '50%':     { transform: 'translateY(-9px)', opacity: '1' },
        },
        brushSweep: {
          '0%':   { clipPath: 'inset(0 100% 0 0)', opacity: '1' },
          '42%':  { clipPath: 'inset(0 0% 0 0)',   opacity: '1' },
          '58%':  { clipPath: 'inset(0 0% 0 0)',   opacity: '1' },
          '100%': { clipPath: 'inset(0 0 0 100%)', opacity: '0' },
        },
        levelBurst: {
          '0%':   { transform: 'scale(0.5)', opacity: '0' },
          '30%':  { transform: 'scale(1.08)', opacity: '1' },
          '60%':  { transform: 'scale(0.97)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        burstRay: {
          '0%':   { transform: 'scaleY(0)', opacity: '0.9' },
          '50%':  { transform: 'scaleY(1)', opacity: '0.7' },
          '100%': { transform: 'scaleY(1)', opacity: '0' },
        },
        /* ── Cyberpunk new keyframes ───────────────────────── */
        glitchBefore: {
          '0%,70%,82%,100%': { opacity: '0', transform: 'none', 'clip-path': 'none' },
          '71%':  { opacity: '0.75', 'clip-path': 'polygon(0 18%, 100% 18%, 100% 44%, 0 44%)', transform: 'translateX(-4px)' },
          '73%':  { opacity: '0.6',  'clip-path': 'polygon(0 62%, 100% 62%, 100% 88%, 0 88%)', transform: 'translateX(3px)' },
          '75%':  { opacity: '0.8',  'clip-path': 'polygon(0 28%, 100% 28%, 100% 52%, 0 52%)', transform: 'translateX(-3px)' },
          '77%':  { opacity: '0.5',  'clip-path': 'polygon(0 72%, 100% 72%, 100% 92%, 0 92%)', transform: 'translateX(2px)' },
          '79%':  { opacity: '0.7',  'clip-path': 'polygon(0 8%,  100% 8%,  100% 26%, 0 26%)', transform: 'translateX(-4px)' },
          '81%':  { opacity: '0.4',  'clip-path': 'polygon(0 44%, 100% 44%, 100% 66%, 0 66%)', transform: 'translateX(1px)' },
        },
        glitchAfter: {
          '0%,73%,85%,100%': { opacity: '0', transform: 'none', 'clip-path': 'none' },
          '74%':  { opacity: '0.65', 'clip-path': 'polygon(0 54%, 100% 54%, 100% 76%, 0 76%)', transform: 'translateX(4px)' },
          '76%':  { opacity: '0.7',  'clip-path': 'polygon(0 8%,  100% 8%,  100% 30%, 0 30%)', transform: 'translateX(-3px)' },
          '78%':  { opacity: '0.55', 'clip-path': 'polygon(0 40%, 100% 40%, 100% 62%, 0 62%)', transform: 'translateX(3px)' },
          '80%':  { opacity: '0.8',  'clip-path': 'polygon(0 75%, 100% 75%, 100% 96%, 0 96%)', transform: 'translateX(-2px)' },
          '82%':  { opacity: '0.6',  'clip-path': 'polygon(0 22%, 100% 22%, 100% 44%, 0 44%)', transform: 'translateX(3px)' },
          '84%':  { opacity: '0.4',  'clip-path': 'polygon(0 50%, 100% 50%, 100% 72%, 0 72%)', transform: 'translateX(-1px)' },
        },
        cardScan: {
          '0%':   { transform: 'translateX(-150%)' },
          '100%': { transform: 'translateX(300%)' },
        },
        neonFlicker: {
          '0%,89%,92%,95%,100%': { opacity: '1' },
          '90%': { opacity: '0.15' },
          '91%': { opacity: '0.9' },
          '93%': { opacity: '0.4' },
          '94%': { opacity: '1' },
          '96%': { opacity: '0.7' },
          '97%': { opacity: '1' },
        },
        cornerPulse: {
          '0%,100%': { opacity: '0.35' },
          '50%':     { opacity: '1' },
        },
        xpFlow: {
          '0%':   { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        rgbShift: {
          '0%,100%': { filter: 'none' },
          '25%':     { filter: 'drop-shadow(-3px 0 rgba(255,0,255,0.75)) drop-shadow(3px 0 rgba(0,255,255,0.75))' },
          '50%':     { filter: 'drop-shadow(3px 0 rgba(255,0,255,0.75)) drop-shadow(-3px 0 rgba(0,255,255,0.75))' },
          '75%':     { filter: 'drop-shadow(-2px 1px rgba(255,0,255,0.6)) drop-shadow(2px -1px rgba(0,255,255,0.6)) brightness(1.3)' },
        },
        borderColorCycle: {
          '0%,100%': { 'border-color': 'rgba(0,240,255,0.55)',   'box-shadow': '0 0 12px rgba(0,240,255,0.25)' },
          '33%':     { 'border-color': 'rgba(155,93,229,0.55)',  'box-shadow': '0 0 12px rgba(155,93,229,0.25)' },
          '66%':     { 'border-color': 'rgba(255,0,127,0.55)',  'box-shadow': '0 0 12px rgba(255,0,127,0.25)' },
        },
        dataFall: {
          '0%':   { opacity: '0', transform: 'translateY(-16px)' },
          '10%':  { opacity: '0.8' },
          '90%':  { opacity: '0.5' },
          '100%': { opacity: '0', transform: 'translateY(100px)' },
        },
        /* ── New background atmosphere keyframes ───────── */
        streamFall: {
          '0%':   { transform: 'translateY(-140px)', opacity: '0' },
          '8%':   { opacity: '1' },
          '88%':  { opacity: '0.6' },
          '100%': { transform: 'translateY(110vh)',  opacity: '0' },
        },
        ambientFloat: {
          '0%,100%': { transform: 'translate(0,    0)    scale(1)'    },
          '25%':     { transform: 'translate(1.8%, -2.8%) scale(1.04)' },
          '50%':     { transform: 'translate(-1.5%, 2.2%) scale(0.96)' },
          '75%':     { transform: 'translate(2.5%,  1.4%) scale(1.02)' },
        },
        holoShimmer: {
          '0%':   { transform: 'translateX(-130%) skewX(-20deg)', opacity: '0' },
          '6%':   { opacity: '1' },
          '55%':  { opacity: '0.85' },
          '65%':  { transform: 'translateX(260%)  skewX(-20deg)', opacity: '0' },
          '100%': { transform: 'translateX(-130%) skewX(-20deg)', opacity: '0' },
        },
        tabGlow: {
          '0%,100%': { opacity: '0.7' },
          '50%':     { opacity: '1'   },
        },
        headerBeam: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(200%)'  },
        },
        /* ── Aggressive cyberpunk keyframes ───────────────── */
        warningPulse: {
          '0%,100%': { opacity: '0.6',  transform: 'scaleX(1)'    },
          '50%':     { opacity: '1',    transform: 'scaleX(1.02)' },
        },
        warningStripe: {
          '0%':   { backgroundPosition: '0 0'    },
          '100%': { backgroundPosition: '40px 0' },
        },
        crosshairSpin: {
          '0%,95%,100%': { transform: 'rotate(0deg)',   opacity: '0.5' },
          '97%':         { transform: 'rotate(90deg)',  opacity: '1'   },
          '99%':         { transform: 'rotate(180deg)', opacity: '0.7' },
        },
        invertFlash: {
          '0%,100%': { filter: 'invert(0) brightness(1)'   },
          '50%':     { filter: 'invert(1) brightness(2)'   },
        },
        statusBlink: {
          '0%,45%,55%,100%': { opacity: '1', boxShadow: '0 0 6px currentColor' },
          '50%':             { opacity: '0.1', boxShadow: '0 0 0px currentColor' },
        },
        bootLine: {
          from: { opacity: '0', width: '0%' },
          to:   { opacity: '1', width: '100%' },
        },
        cursorBlink: {
          '0%,49%': { opacity: '1' },
          '50%,100%': { opacity: '0' },
        },
        matrixDrop: {
          '0%':   { transform: 'translateY(-100%)', opacity: '0' },
          '5%':   { opacity: '1' },
          '90%':  { opacity: '0.8' },
          '100%': { transform: 'translateY(100vh)', opacity: '0' },
        },
      },
      animation: {
        shake:       'shake 0.4s ease',
        pop:         'pop 0.3s ease',
        fadeIn:      'fadeIn 0.4s ease',
        slideUp:     'slideUp 0.35s ease',
        charEnter:   'charEnter 0.45s cubic-bezier(0.34,1.56,0.64,1)',
        flashGreen:  'flashGreen 0.5s ease',
        flashRed:    'flashRed 0.5s ease',
        pulse2:      'pulse2 1s ease infinite',
        coinFloat:   'coinFloat 1.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        wiggle:      'wiggle 0.5s ease',
        shimmer:     'shimmer 2.2s linear infinite',
        bounceCoin:  'bounceCoin 1.2s ease-in-out infinite',
        confettiPop: 'confettiPop 1.4s ease-out forwards',
        glow:        'glow 2s ease-in-out infinite',
        neonPulse:   'neonPulse 2s ease-in-out infinite',
        cyberGlow:   'cyberGlow 1.8s ease-in-out infinite',
        scanLine:    'scanLine 6s linear infinite',
        titleFlicker:'titleFlicker 5s ease-in-out infinite',
        borderFlow:  'borderFlow 4s ease infinite',
        floatY:      'floatY 3s ease-in-out infinite',
        cyberFadeIn: 'cyberFadeIn 0.5s cubic-bezier(0.16,1,0.3,1)',
        explode:     'explode 0.5s ease-out forwards',
        laserShot:   'laserShot 0.25s ease-out forwards',
        particleFly: 'particleFly 0.7s ease-out forwards',
        starTwinkle:  'starTwinkle 3s ease-in-out infinite',
        shipFloat:    'shipFloat 2.5s ease-in-out infinite',
        blink:        'blink 3.5s ease-in-out infinite',
        equipBounce:  'equipBounce 0.55s cubic-bezier(0.34,1.56,0.64,1)',
        starFloat:    'starFloat 2.5s ease-in-out infinite',
        brushSweep:   'brushSweep 0.65s cubic-bezier(0.76,0,0.24,1) forwards',
        levelBurst:   'levelBurst 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        burstRay:     'burstRay 0.7s ease-out forwards',
        /* ── Cyberpunk animations ─────────────────────────── */
        glitchBefore:    'glitchBefore 7s ease-in-out infinite',
        glitchAfter:     'glitchAfter 7s ease-in-out infinite',
        cardScan:        'cardScan 4s ease-in-out infinite',
        neonFlicker:     'neonFlicker 5s ease-in-out infinite',
        cornerPulse:     'cornerPulse 2.5s ease-in-out infinite',
        xpFlow:          'xpFlow 2s linear infinite',
        rgbShift:        'rgbShift 0.2s steps(1, end) infinite',
        borderColorCycle:'borderColorCycle 6s ease-in-out infinite',
        dataFall:        'dataFall 3.5s ease-in-out infinite',
        streamFall:      'streamFall 2.8s linear infinite',
        ambientFloat:    'ambientFloat 15s ease-in-out infinite',
        holoShimmer:     'holoShimmer 6s ease-in-out infinite',
        tabGlow:         'tabGlow 2s ease-in-out infinite',
        headerBeam:      'headerBeam 4s ease-in-out infinite',
        warningPulse:    'warningPulse 1.5s ease-in-out infinite',
        warningStripe:   'warningStripe 1s linear infinite',
        crosshairSpin:   'crosshairSpin 8s ease-in-out infinite',
        invertFlash:     'invertFlash 0.12s steps(1, end) infinite',
        statusBlink:     'statusBlink 1.2s ease-in-out infinite',
        bootLine:        'bootLine 0.4s ease-out forwards',
        cursorBlink:     'cursorBlink 0.8s step-end infinite',
        matrixDrop:      'matrixDrop 2.5s linear infinite',
      },
    },
  },
  plugins: [],
}
